# Generated by Django 2.2.7 on 2020-01-20 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0003_auto_20200118_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='correct_answer',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Mix', on_delete=django.db.models.deletion.CASCADE, to='quizApp.Category'),
        ),
    ]
