# Generated by Django 2.2.7 on 2020-01-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0004_auto_20200120_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.png', upload_to='category_img'),
        ),
    ]
