# Generated by Django 2.2.7 on 2020-01-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0006_auto_20200127_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='category',
            new_name='question',
        ),
    ]
